version: 0.9.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: St2.Client.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: St2.Client\bin\Release\St2.Client.dll
    name: St2.Client.dll
  - path: '**\*.nupkg'