version: 0.9.0.{build}
os: Unstable
branches:
  only:
    - master
install:
  - ps: Get-PackageProvider -Name NuGet -Force
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: St2.Client.sln
  publish_nuget: true
before_build:
  - ps: |
      # Update Manifest File
      $stagingDirectory = (Resolve-Path ..).Path
      $manifest = Join-Path $pwd 'St2.Client.PowerShell\St2.Client.psd1'
      (Get-Content $manifest -Raw).Replace("1.0.0", $env:APPVEYOR_BUILD_VERSION) | Set-Content $manifest
after_build:
  - ps: .\xmldoc2md\xmldoc2md.ps1 -xml "C:\projects\st2client\St2.Client\bin\Release\St2.Client.xml" -xsl "C:\projects\st2client\xmldoc2md\xmldoc2md.xsl" -output "C:\projects\st2client\docs\St2.Client.md"
  - ps: .\DocumentPowerShell.ps1 $($env:powershell_key)
after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: St2.Client\bin\Release\St2.Client.dll
    name: St2.Client.dll
  - path: '**\*.nupkg'
  - path: St2.Client\bin\Release\St2.Client.xml
    name: St2.Client.xml

deploy:
- provider: NuGet
  api_key:
    secure: qJZSv8NQtZWzFP++jAFq1/5abEpcDjW8Wl8rKNwleadnejoLwpdg1+3rUpSG38SN
  artifact: /.*\.nupkg/
  
environment:
  access_token:
    secure: O/sXyJYB0lM0WHQmuoG1LjfB/w9pwx8Pt3HmS13N9MXP7UqbY4/aJvJwemP0tlp2
  powershell_key:
    secure: kfybY3JPmM+VtiK6Uqb0EAhuKVycs7Wa3oaYLLZswT9XfPN34210+FJ7yCuWE7mT

on_success:
  - git config --global user.email "anthony.p.shaw@gmail.com"
  - git config --global user.name "Anthony Shaw"
  - git config --global credential.helper store
  - git config --global push.default simple
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git add docs/
  - git commit -m "Updated docs [skip appveyor]" --allow-empty
  - git push origin HEAD:master
  - ps: Invoke-WebRequest -Uri "https://readthedocs.org/build/st2client" -Method Post
