version: 0.9.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: St2.Client.sln
  publish_nuget: true
after_build:
  - ps: .\xmldoc2md\xmldoc2md.ps1 -xml "C:\projects\st2client\St2.Client\bin\Release\St2.Client.xml" -xsl "C:\projects\st2client\xmldoc2md\xmldoc2md.xsl" -output "C:\projects\st2client\docs\St2.Client.md"
after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: St2.Client\bin\Release\St2.Client.dll
    name: St2.Client.dll
  - path: '**\*.nupkg'
  - path: St2.Client\bin\Release\St2.Client.xml
    name: St2.Client.xml
  
deploy:
- provider: NuGet
  api_key:
    secure: qJZSv8NQtZWzFP++jAFq1/5abEpcDjW8Wl8rKNwleadnejoLwpdg1+3rUpSG38SN
  artifact: /.*\.nupkg/
  
environment:
  access_token:
    secure: O/sXyJYB0lM0WHQmuoG1LjfB/w9pwx8Pt3HmS13N9MXP7UqbY4/aJvJwemP0tlp2

on_success:
  - git config --global user.email "anthony.p.shaw@gmail.com"
  - git config --global user.name "Anthony Shaw"
  - git config --global credential.helper store
  - git config --global push.default simple
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git add docs/St2.Client.md
  - git commit -m "Updated docs [skip appveyor]"
  - git push